//
//  ClockStyleKit.swift
//  SpareTimeAlarm
//
//  Created by Pham Nguyen Nhat Trung on 8/5/15.
//  Copyright (c) 2015 Mirum. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class ClockStyleKit : NSObject {

    //// Drawing Methods

    public class func drawClock(#seconds: CGFloat, minutes: CGFloat, hours: CGFloat, dateInWeek: String, dateInMonth: String) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let fillColor = UIColor(red: 0.500, green: 0.500, blue: 0.500, alpha: 1.000)
        let shadowTint = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        let fillColor2 = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let gradientColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let gradientColor2 = UIColor(red: 0.900, green: 0.900, blue: 0.900, alpha: 1.000)
        let fillColor3 = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)
        let shadowTint2 = UIColor(red: 0.039, green: 0.365, blue: 0.998, alpha: 1.000)
        let strokeColor = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)
        let gradientColor3 = UIColor(red: 0.709, green: 0.709, blue: 0.709, alpha: 1.000)
        let fillColor4 = UIColor(red: 0.060, green: 0.360, blue: 0.932, alpha: 1.000)
        let fillColor5 = UIColor(red: 0.098, green: 0.098, blue: 0.098, alpha: 1.000)
        let fillColor6 = UIColor(red: 0.202, green: 0.202, blue: 0.202, alpha: 1.000)
        let fillColor7 = UIColor(red: 0.991, green: 0.557, blue: 0.034, alpha: 1.000)
        let fillColor8 = UIColor(red: 0.239, green: 0.239, blue: 0.239, alpha: 1.000)
        let fillColor9 = UIColor(red: 0.902, green: 0.346, blue: 0.231, alpha: 1.000)
        let fillColor10 = UIColor(red: 0.200, green: 0.200, blue: 0.200, alpha: 1.000)
        let fillColor11 = UIColor(red: 0.875, green: 0.875, blue: 0.875, alpha: 1.000)
        let fillColor12 = UIColor(red: 0.358, green: 0.606, blue: 0.965, alpha: 1.000)
        let textForeground = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let textForeground2 = UIColor(red: 0.011, green: 0.011, blue: 0.011, alpha: 1.000)

        //// Gradient Declarations
        let gradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [gradientColor.CGColor, gradientColor2.CGColor], [0, 1])
        let gradient2 = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [gradientColor3.CGColor, gradientColor.CGColor], [0, 1])

        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = shadowTint.colorWithAlphaComponent(0.2)
        shadow.shadowOffset = CGSizeMake(668.1, 2.1)
        shadow.shadowBlurRadius = 4
        let shadow2 = NSShadow()
        shadow2.shadowColor = shadowTint2.colorWithAlphaComponent(0.09)
        shadow2.shadowOffset = CGSizeMake(1032.1, -0.1)
        shadow2.shadowBlurRadius = 34
        let shadow6 = NSShadow()
        shadow6.shadowColor = shadowTint.colorWithAlphaComponent(0.18)
        shadow6.shadowOffset = CGSizeMake(60.1, 2.1)
        shadow6.shadowBlurRadius = 2

        //// Variable Declarations
        let secondArrowAngle: CGFloat = -(seconds / 60.0) * 360
        let minuteArrowAngle: CGFloat = (-(minutes / 60.0) + secondArrowAngle / 360.0 / 60.0) * 360
        let hourArrowAngle: CGFloat = ((hours <= 12 ? -hours : 24 - hours) / 12.0 + minuteArrowAngle / 360.0 / 12.0) * 360

        //// ClockInterfaceGroup
        //// Group 4
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip
        let clipPath = UIBezierPath(rect: CGRectMake(0, 0, 334, 336))
        clipPath.addClip()


        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(-653, 15, 296, 296))
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, shadow.shadowOffset, shadow.shadowBlurRadius, (shadow.shadowColor as! UIColor).CGColor)
        fillColor.setFill()
        ovalPath.fill()
        CGContextRestoreGState(context)



        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// Oval 2 Drawing
        var oval2Path = UIBezierPath(ovalInRect: CGRectMake(18, 18, 290, 290))
        fillColor2.setFill()
        oval2Path.fill()


        //// Group 5
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip 2
        var clip2Path = UIBezierPath(ovalInRect: CGRectMake(37, 38, 250, 250))
        clip2Path.addClip()


        //// Oval 3 Drawing
        var oval3Path = UIBezierPath(ovalInRect: CGRectMake(37, 38, 250, 250))
        CGContextSaveGState(context)
        oval3Path.addClip()
        CGContextDrawLinearGradient(context, gradient,
            CGPointMake(162, 38),
            CGPointMake(162, 288),
            UInt32(kCGGradientDrawsBeforeStartLocation) | UInt32(kCGGradientDrawsAfterEndLocation))
        CGContextRestoreGState(context)


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// ClockFrontShadowGroup
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip 3
        var clip3Path = UIBezierPath(ovalInRect: CGRectMake(37, 38, 250, 250))
        clip3Path.addClip()


        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(-1094, -61))
        bezierPath.addLineToPoint(CGPointMake(-578, -61))
        bezierPath.addLineToPoint(CGPointMake(-578, 455))
        bezierPath.addLineToPoint(CGPointMake(-1094, 455))
        bezierPath.addLineToPoint(CGPointMake(-1094, -61))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(-870, 288))
        bezierPath.addCurveToPoint(CGPointMake(-745, 163), controlPoint1: CGPointMake(-800.96, 288), controlPoint2: CGPointMake(-745, 232.04))
        bezierPath.addCurveToPoint(CGPointMake(-870, 38), controlPoint1: CGPointMake(-745, 93.96), controlPoint2: CGPointMake(-800.96, 38))
        bezierPath.addCurveToPoint(CGPointMake(-995, 163), controlPoint1: CGPointMake(-939.04, 38), controlPoint2: CGPointMake(-995, 93.96))
        bezierPath.addCurveToPoint(CGPointMake(-870, 288), controlPoint1: CGPointMake(-995, 232.04), controlPoint2: CGPointMake(-939.04, 288))
        bezierPath.closePath()
        bezierPath.usesEvenOddFillRule = true;

        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, shadow2.shadowOffset, shadow2.shadowBlurRadius, (shadow2.shadowColor as! UIColor).CGColor)
        fillColor3.setFill()
        bezierPath.fill()
        CGContextRestoreGState(context)



        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// Group 7
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip 4
        var clip4Path = UIBezierPath(ovalInRect: CGRectMake(37, 38, 250, 250))
        clip4Path.addClip()


        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(-1094, -61))
        bezier2Path.addLineToPoint(CGPointMake(-578, -61))
        bezier2Path.addLineToPoint(CGPointMake(-578, 455))
        bezier2Path.addLineToPoint(CGPointMake(-1094, 455))
        bezier2Path.addLineToPoint(CGPointMake(-1094, -61))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(-870, 288))
        bezier2Path.addCurveToPoint(CGPointMake(-745, 163), controlPoint1: CGPointMake(-800.96, 288), controlPoint2: CGPointMake(-745, 232.04))
        bezier2Path.addCurveToPoint(CGPointMake(-870, 38), controlPoint1: CGPointMake(-745, 93.96), controlPoint2: CGPointMake(-800.96, 38))
        bezier2Path.addCurveToPoint(CGPointMake(-995, 163), controlPoint1: CGPointMake(-939.04, 38), controlPoint2: CGPointMake(-995, 93.96))
        bezier2Path.addCurveToPoint(CGPointMake(-870, 288), controlPoint1: CGPointMake(-995, 232.04), controlPoint2: CGPointMake(-939.04, 288))
        bezier2Path.closePath()
        strokeColor.setStroke()
        bezier2Path.lineWidth = 52
        bezier2Path.stroke()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// ClockInnerCentralSmallCircleGroup
        CGContextSaveGState(context)
        CGContextSetAlpha(context, 0.4)
        CGContextBeginTransparencyLayer(context, nil)


        //// innerSmallCircle Drawing
        var innerSmallCirclePath = UIBezierPath(ovalInRect: CGRectMake(144, 145, 36, 36))
        CGContextSaveGState(context)
        innerSmallCirclePath.addClip()
        CGContextDrawLinearGradient(context, gradient2,
            CGPointMake(162, 145),
            CGPointMake(162, 181),
            UInt32(kCGGradientDrawsBeforeStartLocation) | UInt32(kCGGradientDrawsAfterEndLocation))
        CGContextRestoreGState(context)


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// ClockRoundBorderGroup
        CGContextSaveGState(context)
        CGContextSetAlpha(context, 0.08)
        CGContextBeginTransparencyLayer(context, nil)


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(162, 288))
        bezier3Path.addCurveToPoint(CGPointMake(287, 163), controlPoint1: CGPointMake(231.04, 288), controlPoint2: CGPointMake(287, 232.04))
        bezier3Path.addCurveToPoint(CGPointMake(162, 38), controlPoint1: CGPointMake(287, 93.96), controlPoint2: CGPointMake(231.04, 38))
        bezier3Path.addCurveToPoint(CGPointMake(37, 163), controlPoint1: CGPointMake(92.96, 38), controlPoint2: CGPointMake(37, 93.96))
        bezier3Path.addCurveToPoint(CGPointMake(162, 288), controlPoint1: CGPointMake(37, 232.04), controlPoint2: CGPointMake(92.96, 288))
        bezier3Path.closePath()
        bezier3Path.moveToPoint(CGPointMake(162, 284))
        bezier3Path.addCurveToPoint(CGPointMake(283, 163), controlPoint1: CGPointMake(228.83, 284), controlPoint2: CGPointMake(283, 229.83))
        bezier3Path.addCurveToPoint(CGPointMake(162, 42), controlPoint1: CGPointMake(283, 96.17), controlPoint2: CGPointMake(228.83, 42))
        bezier3Path.addCurveToPoint(CGPointMake(41, 163), controlPoint1: CGPointMake(95.17, 42), controlPoint2: CGPointMake(41, 96.17))
        bezier3Path.addCurveToPoint(CGPointMake(162, 284), controlPoint1: CGPointMake(41, 229.83), controlPoint2: CGPointMake(95.17, 284))
        bezier3Path.closePath()
        bezier3Path.usesEvenOddFillRule = true;

        fillColor4.setFill()
        bezier3Path.fill()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// orangeDot Drawing
        var orangeDotPath = UIBezierPath(ovalInRect: CGRectMake(160, 284, 4, 4))
        fillColor9.setFill()
        orangeDotPath.fill()


        //// Bezier 4 Drawing
        var bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(162, 53))
        bezier4Path.addCurveToPoint(CGPointMake(164, 51), controlPoint1: CGPointMake(163.1, 53), controlPoint2: CGPointMake(164, 52.1))
        bezier4Path.addCurveToPoint(CGPointMake(162, 49), controlPoint1: CGPointMake(164, 49.9), controlPoint2: CGPointMake(163.1, 49))
        bezier4Path.addCurveToPoint(CGPointMake(160, 51), controlPoint1: CGPointMake(160.9, 49), controlPoint2: CGPointMake(160, 49.9))
        bezier4Path.addCurveToPoint(CGPointMake(162, 53), controlPoint1: CGPointMake(160, 52.1), controlPoint2: CGPointMake(160.9, 53))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(162, 277))
        bezier4Path.addCurveToPoint(CGPointMake(164, 275), controlPoint1: CGPointMake(163.1, 277), controlPoint2: CGPointMake(164, 276.1))
        bezier4Path.addCurveToPoint(CGPointMake(162, 273), controlPoint1: CGPointMake(164, 273.9), controlPoint2: CGPointMake(163.1, 273))
        bezier4Path.addCurveToPoint(CGPointMake(160, 275), controlPoint1: CGPointMake(160.9, 273), controlPoint2: CGPointMake(160, 273.9))
        bezier4Path.addCurveToPoint(CGPointMake(162, 277), controlPoint1: CGPointMake(160, 276.1), controlPoint2: CGPointMake(160.9, 277))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(107, 67.74))
        bezier4Path.addCurveToPoint(CGPointMake(107.73, 65.01), controlPoint1: CGPointMake(107.96, 67.18), controlPoint2: CGPointMake(108.28, 65.96))
        bezier4Path.addCurveToPoint(CGPointMake(105, 64.27), controlPoint1: CGPointMake(107.18, 64.05), controlPoint2: CGPointMake(105.96, 63.72))
        bezier4Path.addCurveToPoint(CGPointMake(104.27, 67.01), controlPoint1: CGPointMake(104.04, 64.83), controlPoint2: CGPointMake(103.72, 66.05))
        bezier4Path.addCurveToPoint(CGPointMake(107, 67.74), controlPoint1: CGPointMake(104.82, 67.96), controlPoint2: CGPointMake(106.04, 68.29))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(219, 261.73))
        bezier4Path.addCurveToPoint(CGPointMake(219.73, 258.99), controlPoint1: CGPointMake(219.96, 261.17), controlPoint2: CGPointMake(220.28, 259.95))
        bezier4Path.addCurveToPoint(CGPointMake(217, 258.26), controlPoint1: CGPointMake(219.18, 258.04), controlPoint2: CGPointMake(217.96, 257.71))
        bezier4Path.addCurveToPoint(CGPointMake(216.27, 260.99), controlPoint1: CGPointMake(216.04, 258.82), controlPoint2: CGPointMake(215.72, 260.04))
        bezier4Path.addCurveToPoint(CGPointMake(219, 261.73), controlPoint1: CGPointMake(216.82, 261.95), controlPoint2: CGPointMake(218.04, 262.28))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(66.74, 108))
        bezier4Path.addCurveToPoint(CGPointMake(66.01, 105.27), controlPoint1: CGPointMake(67.29, 107.04), controlPoint2: CGPointMake(66.96, 105.82))
        bezier4Path.addCurveToPoint(CGPointMake(63.27, 106), controlPoint1: CGPointMake(65.05, 104.72), controlPoint2: CGPointMake(63.83, 105.04))
        bezier4Path.addCurveToPoint(CGPointMake(64.01, 108.73), controlPoint1: CGPointMake(62.72, 106.96), controlPoint2: CGPointMake(63.05, 108.18))
        bezier4Path.addCurveToPoint(CGPointMake(66.74, 108), controlPoint1: CGPointMake(64.96, 109.28), controlPoint2: CGPointMake(66.18, 108.96))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(260.73, 220))
        bezier4Path.addCurveToPoint(CGPointMake(259.99, 217.27), controlPoint1: CGPointMake(261.28, 219.04), controlPoint2: CGPointMake(260.95, 217.82))
        bezier4Path.addCurveToPoint(CGPointMake(257.26, 218), controlPoint1: CGPointMake(259.04, 216.72), controlPoint2: CGPointMake(257.82, 217.04))
        bezier4Path.addCurveToPoint(CGPointMake(257.99, 220.73), controlPoint1: CGPointMake(256.71, 218.96), controlPoint2: CGPointMake(257.04, 220.18))
        bezier4Path.addCurveToPoint(CGPointMake(260.73, 220), controlPoint1: CGPointMake(258.95, 221.28), controlPoint2: CGPointMake(260.17, 220.96))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(272, 163))
        bezier4Path.addCurveToPoint(CGPointMake(274, 165), controlPoint1: CGPointMake(272, 164.1), controlPoint2: CGPointMake(272.9, 165))
        bezier4Path.addCurveToPoint(CGPointMake(276, 163), controlPoint1: CGPointMake(275.1, 165), controlPoint2: CGPointMake(276, 164.1))
        bezier4Path.addCurveToPoint(CGPointMake(274, 161), controlPoint1: CGPointMake(276, 161.9), controlPoint2: CGPointMake(275.1, 161))
        bezier4Path.addCurveToPoint(CGPointMake(272, 163), controlPoint1: CGPointMake(272.9, 161), controlPoint2: CGPointMake(272, 161.9))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(48, 163))
        bezier4Path.addCurveToPoint(CGPointMake(50, 165), controlPoint1: CGPointMake(48, 164.1), controlPoint2: CGPointMake(48.9, 165))
        bezier4Path.addCurveToPoint(CGPointMake(52, 163), controlPoint1: CGPointMake(51.1, 165), controlPoint2: CGPointMake(52, 164.1))
        bezier4Path.addCurveToPoint(CGPointMake(50, 161), controlPoint1: CGPointMake(52, 161.9), controlPoint2: CGPointMake(51.1, 161))
        bezier4Path.addCurveToPoint(CGPointMake(48, 163), controlPoint1: CGPointMake(48.9, 161), controlPoint2: CGPointMake(48, 161.9))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(217, 67.74))
        bezier4Path.addCurveToPoint(CGPointMake(219.73, 67.01), controlPoint1: CGPointMake(217.96, 68.29), controlPoint2: CGPointMake(219.18, 67.96))
        bezier4Path.addCurveToPoint(CGPointMake(219, 64.27), controlPoint1: CGPointMake(220.28, 66.05), controlPoint2: CGPointMake(219.96, 64.83))
        bezier4Path.addCurveToPoint(CGPointMake(216.27, 65.01), controlPoint1: CGPointMake(218.04, 63.72), controlPoint2: CGPointMake(216.82, 64.05))
        bezier4Path.addCurveToPoint(CGPointMake(217, 67.74), controlPoint1: CGPointMake(215.72, 65.96), controlPoint2: CGPointMake(216.04, 67.18))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(105, 261.73))
        bezier4Path.addCurveToPoint(CGPointMake(107.73, 260.99), controlPoint1: CGPointMake(105.96, 262.28), controlPoint2: CGPointMake(107.18, 261.95))
        bezier4Path.addCurveToPoint(CGPointMake(107, 258.26), controlPoint1: CGPointMake(108.28, 260.04), controlPoint2: CGPointMake(107.96, 258.82))
        bezier4Path.addCurveToPoint(CGPointMake(104.27, 258.99), controlPoint1: CGPointMake(106.04, 257.71), controlPoint2: CGPointMake(104.82, 258.04))
        bezier4Path.addCurveToPoint(CGPointMake(105, 261.73), controlPoint1: CGPointMake(103.72, 259.95), controlPoint2: CGPointMake(104.04, 261.17))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(257.26, 108))
        bezier4Path.addCurveToPoint(CGPointMake(259.99, 108.73), controlPoint1: CGPointMake(257.82, 108.96), controlPoint2: CGPointMake(259.04, 109.28))
        bezier4Path.addCurveToPoint(CGPointMake(260.73, 106), controlPoint1: CGPointMake(260.95, 108.18), controlPoint2: CGPointMake(261.28, 106.96))
        bezier4Path.addCurveToPoint(CGPointMake(257.99, 105.27), controlPoint1: CGPointMake(260.17, 105.04), controlPoint2: CGPointMake(258.95, 104.72))
        bezier4Path.addCurveToPoint(CGPointMake(257.26, 108), controlPoint1: CGPointMake(257.04, 105.82), controlPoint2: CGPointMake(256.71, 107.04))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(63.27, 220))
        bezier4Path.addCurveToPoint(CGPointMake(66.01, 220.73), controlPoint1: CGPointMake(63.83, 220.96), controlPoint2: CGPointMake(65.05, 221.28))
        bezier4Path.addCurveToPoint(CGPointMake(66.74, 218), controlPoint1: CGPointMake(66.96, 220.18), controlPoint2: CGPointMake(67.29, 218.96))
        bezier4Path.addCurveToPoint(CGPointMake(64.01, 217.27), controlPoint1: CGPointMake(66.18, 217.04), controlPoint2: CGPointMake(64.96, 216.72))
        bezier4Path.addCurveToPoint(CGPointMake(63.27, 220), controlPoint1: CGPointMake(63.05, 217.82), controlPoint2: CGPointMake(62.72, 219.04))
        bezier4Path.closePath()
        bezier4Path.usesEvenOddFillRule = true;

        fillColor10.setFill()
        bezier4Path.fill()


        //// Group 10
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip 5
        var clip5Path = UIBezierPath()
        clip5Path.moveToPoint(CGPointMake(173.6, 52.61))
        clip5Path.addCurveToPoint(CGPointMake(174.7, 51.72), controlPoint1: CGPointMake(174.15, 52.67), controlPoint2: CGPointMake(174.64, 52.27))
        clip5Path.addCurveToPoint(CGPointMake(173.81, 50.62), controlPoint1: CGPointMake(174.76, 51.17), controlPoint2: CGPointMake(174.36, 50.68))
        clip5Path.addCurveToPoint(CGPointMake(172.71, 51.51), controlPoint1: CGPointMake(173.26, 50.56), controlPoint2: CGPointMake(172.77, 50.96))
        clip5Path.addCurveToPoint(CGPointMake(173.6, 52.61), controlPoint1: CGPointMake(172.65, 52.06), controlPoint2: CGPointMake(173.05, 52.55))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(150.19, 275.38))
        clip5Path.addCurveToPoint(CGPointMake(151.29, 274.49), controlPoint1: CGPointMake(150.74, 275.44), controlPoint2: CGPointMake(151.23, 275.04))
        clip5Path.addCurveToPoint(CGPointMake(150.4, 273.39), controlPoint1: CGPointMake(151.35, 273.94), controlPoint2: CGPointMake(150.95, 273.45))
        clip5Path.addCurveToPoint(CGPointMake(149.3, 274.28), controlPoint1: CGPointMake(149.85, 273.33), controlPoint2: CGPointMake(149.36, 273.73))
        clip5Path.addCurveToPoint(CGPointMake(150.19, 275.38), controlPoint1: CGPointMake(149.24, 274.83), controlPoint2: CGPointMake(149.64, 275.32))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(116.85, 61.6))
        clip5Path.addCurveToPoint(CGPointMake(117.36, 60.28), controlPoint1: CGPointMake(117.36, 61.37), controlPoint2: CGPointMake(117.58, 60.78))
        clip5Path.addCurveToPoint(CGPointMake(116.04, 59.77), controlPoint1: CGPointMake(117.13, 59.77), controlPoint2: CGPointMake(116.54, 59.54))
        clip5Path.addCurveToPoint(CGPointMake(115.53, 61.09), controlPoint1: CGPointMake(115.53, 59.99), controlPoint2: CGPointMake(115.31, 60.59))
        clip5Path.addCurveToPoint(CGPointMake(116.85, 61.6), controlPoint1: CGPointMake(115.76, 61.59), controlPoint2: CGPointMake(116.35, 61.82))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(207.96, 266.23))
        clip5Path.addCurveToPoint(CGPointMake(208.47, 264.91), controlPoint1: CGPointMake(208.47, 266.01), controlPoint2: CGPointMake(208.69, 265.41))
        clip5Path.addCurveToPoint(CGPointMake(207.15, 264.4), controlPoint1: CGPointMake(208.24, 264.41), controlPoint2: CGPointMake(207.65, 264.18))
        clip5Path.addCurveToPoint(CGPointMake(206.64, 265.72), controlPoint1: CGPointMake(206.64, 264.63), controlPoint2: CGPointMake(206.42, 265.22))
        clip5Path.addCurveToPoint(CGPointMake(207.96, 266.23), controlPoint1: CGPointMake(206.87, 266.23), controlPoint2: CGPointMake(207.46, 266.46))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(72.2, 97.76))
        clip5Path.addCurveToPoint(CGPointMake(71.98, 96.36), controlPoint1: CGPointMake(72.52, 97.31), controlPoint2: CGPointMake(72.42, 96.68))
        clip5Path.addCurveToPoint(CGPointMake(70.58, 96.58), controlPoint1: CGPointMake(71.53, 96.03), controlPoint2: CGPointMake(70.91, 96.13))
        clip5Path.addCurveToPoint(CGPointMake(70.8, 97.98), controlPoint1: CGPointMake(70.26, 97.03), controlPoint2: CGPointMake(70.36, 97.65))
        clip5Path.addCurveToPoint(CGPointMake(72.2, 97.76), controlPoint1: CGPointMake(71.25, 98.3), controlPoint2: CGPointMake(71.87, 98.2))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(253.42, 229.42))
        clip5Path.addCurveToPoint(CGPointMake(253.2, 228.02), controlPoint1: CGPointMake(253.74, 228.97), controlPoint2: CGPointMake(253.64, 228.35))
        clip5Path.addCurveToPoint(CGPointMake(251.8, 228.24), controlPoint1: CGPointMake(252.75, 227.7), controlPoint2: CGPointMake(252.13, 227.8))
        clip5Path.addCurveToPoint(CGPointMake(252.02, 229.64), controlPoint1: CGPointMake(251.48, 228.69), controlPoint2: CGPointMake(251.58, 229.32))
        clip5Path.addCurveToPoint(CGPointMake(253.42, 229.42), controlPoint1: CGPointMake(252.47, 229.97), controlPoint2: CGPointMake(253.09, 229.87))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(272.39, 174.6))
        clip5Path.addCurveToPoint(CGPointMake(273.28, 175.7), controlPoint1: CGPointMake(272.33, 175.15), controlPoint2: CGPointMake(272.73, 175.64))
        clip5Path.addCurveToPoint(CGPointMake(274.38, 174.81), controlPoint1: CGPointMake(273.83, 175.76), controlPoint2: CGPointMake(274.32, 175.36))
        clip5Path.addCurveToPoint(CGPointMake(273.49, 173.71), controlPoint1: CGPointMake(274.44, 174.26), controlPoint2: CGPointMake(274.04, 173.77))
        clip5Path.addCurveToPoint(CGPointMake(272.39, 174.6), controlPoint1: CGPointMake(272.94, 173.65), controlPoint2: CGPointMake(272.45, 174.05))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(49.62, 151.19))
        clip5Path.addCurveToPoint(CGPointMake(50.51, 152.29), controlPoint1: CGPointMake(49.56, 151.74), controlPoint2: CGPointMake(49.96, 152.23))
        clip5Path.addCurveToPoint(CGPointMake(51.61, 151.4), controlPoint1: CGPointMake(51.06, 152.35), controlPoint2: CGPointMake(51.55, 151.95))
        clip5Path.addCurveToPoint(CGPointMake(50.72, 150.3), controlPoint1: CGPointMake(51.67, 150.85), controlPoint2: CGPointMake(51.27, 150.36))
        clip5Path.addCurveToPoint(CGPointMake(49.62, 151.19), controlPoint1: CGPointMake(50.17, 150.24), controlPoint2: CGPointMake(49.68, 150.64))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(227.24, 73.2))
        clip5Path.addCurveToPoint(CGPointMake(228.64, 72.98), controlPoint1: CGPointMake(227.69, 73.52), controlPoint2: CGPointMake(228.32, 73.42))
        clip5Path.addCurveToPoint(CGPointMake(228.42, 71.58), controlPoint1: CGPointMake(228.97, 72.53), controlPoint2: CGPointMake(228.87, 71.91))
        clip5Path.addCurveToPoint(CGPointMake(227.02, 71.8), controlPoint1: CGPointMake(227.97, 71.26), controlPoint2: CGPointMake(227.35, 71.36))
        clip5Path.addCurveToPoint(CGPointMake(227.24, 73.2), controlPoint1: CGPointMake(226.7, 72.25), controlPoint2: CGPointMake(226.8, 72.87))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(95.58, 254.42))
        clip5Path.addCurveToPoint(CGPointMake(96.98, 254.2), controlPoint1: CGPointMake(96.03, 254.74), controlPoint2: CGPointMake(96.65, 254.64))
        clip5Path.addCurveToPoint(CGPointMake(96.76, 252.8), controlPoint1: CGPointMake(97.3, 253.75), controlPoint2: CGPointMake(97.2, 253.13))
        clip5Path.addCurveToPoint(CGPointMake(95.36, 253.02), controlPoint1: CGPointMake(96.31, 252.48), controlPoint2: CGPointMake(95.68, 252.58))
        clip5Path.addCurveToPoint(CGPointMake(95.58, 254.42), controlPoint1: CGPointMake(95.03, 253.47), controlPoint2: CGPointMake(95.13, 254.09))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(263.4, 117.85))
        clip5Path.addCurveToPoint(CGPointMake(264.72, 118.36), controlPoint1: CGPointMake(263.63, 118.36), controlPoint2: CGPointMake(264.22, 118.58))
        clip5Path.addCurveToPoint(CGPointMake(265.23, 117.04), controlPoint1: CGPointMake(265.23, 118.13), controlPoint2: CGPointMake(265.46, 117.54))
        clip5Path.addCurveToPoint(CGPointMake(263.91, 116.53), controlPoint1: CGPointMake(265.01, 116.53), controlPoint2: CGPointMake(264.41, 116.31))
        clip5Path.addCurveToPoint(CGPointMake(263.4, 117.85), controlPoint1: CGPointMake(263.41, 116.76), controlPoint2: CGPointMake(263.18, 117.35))
        clip5Path.closePath()
        clip5Path.moveToPoint(CGPointMake(58.77, 208.96))
        clip5Path.addCurveToPoint(CGPointMake(60.09, 209.47), controlPoint1: CGPointMake(58.99, 209.47), controlPoint2: CGPointMake(59.59, 209.69))
        clip5Path.addCurveToPoint(CGPointMake(60.6, 208.15), controlPoint1: CGPointMake(60.59, 209.24), controlPoint2: CGPointMake(60.82, 208.65))
        clip5Path.addCurveToPoint(CGPointMake(59.28, 207.64), controlPoint1: CGPointMake(60.37, 207.64), controlPoint2: CGPointMake(59.78, 207.42))
        clip5Path.addCurveToPoint(CGPointMake(58.77, 208.96), controlPoint1: CGPointMake(58.77, 207.87), controlPoint2: CGPointMake(58.54, 208.46))
        clip5Path.closePath()
        clip5Path.usesEvenOddFillRule = true;

        clip5Path.addClip()


        //// Rectangle 2 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 162, 163)
        CGContextRotateCTM(context, 6 * CGFloat(M_PI) / 180)

        let rectangle2Path = UIBezierPath(rect: CGRectMake(-118, -118, 236, 236))
        fillColor10.setFill()
        rectangle2Path.fill()

        CGContextRestoreGState(context)


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// ClockSmallBlackDotGroup
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip 6
        var clip6Path = UIBezierPath()
        clip6Path.moveToPoint(CGPointMake(185.08, 54.43))
        clip6Path.addCurveToPoint(CGPointMake(186.26, 53.66), controlPoint1: CGPointMake(185.62, 54.54), controlPoint2: CGPointMake(186.15, 54.2))
        clip6Path.addCurveToPoint(CGPointMake(185.49, 52.47), controlPoint1: CGPointMake(186.38, 53.12), controlPoint2: CGPointMake(186.03, 52.58))
        clip6Path.addCurveToPoint(CGPointMake(184.31, 53.24), controlPoint1: CGPointMake(184.95, 52.35), controlPoint2: CGPointMake(184.42, 52.7))
        clip6Path.addCurveToPoint(CGPointMake(185.08, 54.43), controlPoint1: CGPointMake(184.19, 53.78), controlPoint2: CGPointMake(184.54, 54.31))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(138.51, 273.53))
        clip6Path.addCurveToPoint(CGPointMake(139.69, 272.76), controlPoint1: CGPointMake(139.05, 273.65), controlPoint2: CGPointMake(139.58, 273.3))
        clip6Path.addCurveToPoint(CGPointMake(138.92, 271.57), controlPoint1: CGPointMake(139.81, 272.22), controlPoint2: CGPointMake(139.46, 271.69))
        clip6Path.addCurveToPoint(CGPointMake(137.74, 272.34), controlPoint1: CGPointMake(138.38, 271.46), controlPoint2: CGPointMake(137.85, 271.8))
        clip6Path.addCurveToPoint(CGPointMake(138.51, 273.53), controlPoint1: CGPointMake(137.62, 272.88), controlPoint2: CGPointMake(137.97, 273.42))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(127.7, 57.43))
        clip6Path.addCurveToPoint(CGPointMake(128.34, 56.17), controlPoint1: CGPointMake(128.22, 57.26), controlPoint2: CGPointMake(128.51, 56.7))
        clip6Path.addCurveToPoint(CGPointMake(127.08, 55.53), controlPoint1: CGPointMake(128.17, 55.65), controlPoint2: CGPointMake(127.61, 55.36))
        clip6Path.addCurveToPoint(CGPointMake(126.44, 56.79), controlPoint1: CGPointMake(126.56, 55.7), controlPoint2: CGPointMake(126.27, 56.27))
        clip6Path.addCurveToPoint(CGPointMake(127.7, 57.43), controlPoint1: CGPointMake(126.61, 57.32), controlPoint2: CGPointMake(127.17, 57.6))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(196.92, 270.47))
        clip6Path.addCurveToPoint(CGPointMake(197.56, 269.21), controlPoint1: CGPointMake(197.44, 270.3), controlPoint2: CGPointMake(197.73, 269.73))
        clip6Path.addCurveToPoint(CGPointMake(196.3, 268.57), controlPoint1: CGPointMake(197.39, 268.68), controlPoint2: CGPointMake(196.83, 268.4))
        clip6Path.addCurveToPoint(CGPointMake(195.66, 269.83), controlPoint1: CGPointMake(195.78, 268.74), controlPoint2: CGPointMake(195.49, 269.3))
        clip6Path.addCurveToPoint(CGPointMake(196.92, 270.47), controlPoint1: CGPointMake(195.83, 270.35), controlPoint2: CGPointMake(196.39, 270.64))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(79.51, 88.73))
        clip6Path.addCurveToPoint(CGPointMake(79.44, 87.31), controlPoint1: CGPointMake(79.88, 88.32), controlPoint2: CGPointMake(79.85, 87.68))
        clip6Path.addCurveToPoint(CGPointMake(78.02, 87.39), controlPoint1: CGPointMake(79.03, 86.94), controlPoint2: CGPointMake(78.39, 86.98))
        clip6Path.addCurveToPoint(CGPointMake(78.1, 88.8), controlPoint1: CGPointMake(77.66, 87.8), controlPoint2: CGPointMake(77.69, 88.43))
        clip6Path.addCurveToPoint(CGPointMake(79.51, 88.73), controlPoint1: CGPointMake(78.51, 89.17), controlPoint2: CGPointMake(79.14, 89.14))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(245.98, 238.61))
        clip6Path.addCurveToPoint(CGPointMake(245.9, 237.2), controlPoint1: CGPointMake(246.34, 238.2), controlPoint2: CGPointMake(246.31, 237.57))
        clip6Path.addCurveToPoint(CGPointMake(244.49, 237.27), controlPoint1: CGPointMake(245.49, 236.83), controlPoint2: CGPointMake(244.86, 236.86))
        clip6Path.addCurveToPoint(CGPointMake(244.56, 238.69), controlPoint1: CGPointMake(244.12, 237.68), controlPoint2: CGPointMake(244.15, 238.32))
        clip6Path.addCurveToPoint(CGPointMake(245.98, 238.61), controlPoint1: CGPointMake(244.97, 239.06), controlPoint2: CGPointMake(245.61, 239.02))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(270.57, 186.08))
        clip6Path.addCurveToPoint(CGPointMake(271.34, 187.26), controlPoint1: CGPointMake(270.46, 186.62), controlPoint2: CGPointMake(270.8, 187.15))
        clip6Path.addCurveToPoint(CGPointMake(272.53, 186.49), controlPoint1: CGPointMake(271.88, 187.38), controlPoint2: CGPointMake(272.42, 187.03))
        clip6Path.addCurveToPoint(CGPointMake(271.76, 185.31), controlPoint1: CGPointMake(272.65, 185.95), controlPoint2: CGPointMake(272.3, 185.42))
        clip6Path.addCurveToPoint(CGPointMake(270.57, 186.08), controlPoint1: CGPointMake(271.22, 185.19), controlPoint2: CGPointMake(270.69, 185.54))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(51.47, 139.51))
        clip6Path.addCurveToPoint(CGPointMake(52.24, 140.69), controlPoint1: CGPointMake(51.35, 140.05), controlPoint2: CGPointMake(51.7, 140.58))
        clip6Path.addCurveToPoint(CGPointMake(53.43, 139.92), controlPoint1: CGPointMake(52.78, 140.81), controlPoint2: CGPointMake(53.31, 140.46))
        clip6Path.addCurveToPoint(CGPointMake(52.66, 138.74), controlPoint1: CGPointMake(53.54, 139.38), controlPoint2: CGPointMake(53.2, 138.85))
        clip6Path.addCurveToPoint(CGPointMake(51.47, 139.51), controlPoint1: CGPointMake(52.12, 138.62), controlPoint2: CGPointMake(51.58, 138.97))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(236.27, 80.51))
        clip6Path.addCurveToPoint(CGPointMake(237.69, 80.44), controlPoint1: CGPointMake(236.68, 80.88), controlPoint2: CGPointMake(237.32, 80.85))
        clip6Path.addCurveToPoint(CGPointMake(237.61, 79.02), controlPoint1: CGPointMake(238.06, 80.03), controlPoint2: CGPointMake(238.02, 79.39))
        clip6Path.addCurveToPoint(CGPointMake(236.2, 79.1), controlPoint1: CGPointMake(237.2, 78.66), controlPoint2: CGPointMake(236.57, 78.69))
        clip6Path.addCurveToPoint(CGPointMake(236.27, 80.51), controlPoint1: CGPointMake(235.83, 79.51), controlPoint2: CGPointMake(235.86, 80.14))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(86.39, 246.98))
        clip6Path.addCurveToPoint(CGPointMake(87.8, 246.9), controlPoint1: CGPointMake(86.8, 247.34), controlPoint2: CGPointMake(87.43, 247.31))
        clip6Path.addCurveToPoint(CGPointMake(87.73, 245.49), controlPoint1: CGPointMake(88.17, 246.49), controlPoint2: CGPointMake(88.14, 245.86))
        clip6Path.addCurveToPoint(CGPointMake(86.31, 245.56), controlPoint1: CGPointMake(87.32, 245.12), controlPoint2: CGPointMake(86.68, 245.15))
        clip6Path.addCurveToPoint(CGPointMake(86.39, 246.98), controlPoint1: CGPointMake(85.94, 245.97), controlPoint2: CGPointMake(85.98, 246.61))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(267.57, 128.7))
        clip6Path.addCurveToPoint(CGPointMake(268.83, 129.34), controlPoint1: CGPointMake(267.74, 129.22), controlPoint2: CGPointMake(268.3, 129.51))
        clip6Path.addCurveToPoint(CGPointMake(269.47, 128.08), controlPoint1: CGPointMake(269.35, 129.17), controlPoint2: CGPointMake(269.64, 128.61))
        clip6Path.addCurveToPoint(CGPointMake(268.21, 127.44), controlPoint1: CGPointMake(269.3, 127.56), controlPoint2: CGPointMake(268.73, 127.27))
        clip6Path.addCurveToPoint(CGPointMake(267.57, 128.7), controlPoint1: CGPointMake(267.68, 127.61), controlPoint2: CGPointMake(267.4, 128.17))
        clip6Path.closePath()
        clip6Path.moveToPoint(CGPointMake(54.53, 197.92))
        clip6Path.addCurveToPoint(CGPointMake(55.79, 198.56), controlPoint1: CGPointMake(54.7, 198.44), controlPoint2: CGPointMake(55.27, 198.73))
        clip6Path.addCurveToPoint(CGPointMake(56.43, 197.3), controlPoint1: CGPointMake(56.32, 198.39), controlPoint2: CGPointMake(56.6, 197.83))
        clip6Path.addCurveToPoint(CGPointMake(55.17, 196.66), controlPoint1: CGPointMake(56.26, 196.78), controlPoint2: CGPointMake(55.7, 196.49))
        clip6Path.addCurveToPoint(CGPointMake(54.53, 197.92), controlPoint1: CGPointMake(54.65, 196.83), controlPoint2: CGPointMake(54.36, 197.39))
        clip6Path.closePath()
        clip6Path.usesEvenOddFillRule = true;

        clip6Path.addClip()


        //// Rectangle 3 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 162, 163)
        CGContextRotateCTM(context, 12 * CGFloat(M_PI) / 180)

        let rectangle3Path = UIBezierPath(rect: CGRectMake(-118, -118, 236, 236))
        fillColor10.setFill()
        rectangle3Path.fill()

        CGContextRestoreGState(context)


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// ClockBlueDotGroup
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip 7
        var clip7Path = UIBezierPath()
        clip7Path.moveToPoint(CGPointMake(196.3, 57.43))
        clip7Path.addCurveToPoint(CGPointMake(197.56, 56.79), controlPoint1: CGPointMake(196.83, 57.6), controlPoint2: CGPointMake(197.39, 57.32))
        clip7Path.addCurveToPoint(CGPointMake(196.92, 55.53), controlPoint1: CGPointMake(197.73, 56.27), controlPoint2: CGPointMake(197.44, 55.7))
        clip7Path.addCurveToPoint(CGPointMake(195.66, 56.17), controlPoint1: CGPointMake(196.39, 55.36), controlPoint2: CGPointMake(195.83, 55.65))
        clip7Path.addCurveToPoint(CGPointMake(196.3, 57.43), controlPoint1: CGPointMake(195.49, 56.7), controlPoint2: CGPointMake(195.78, 57.26))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(127.08, 270.47))
        clip7Path.addCurveToPoint(CGPointMake(128.34, 269.83), controlPoint1: CGPointMake(127.61, 270.64), controlPoint2: CGPointMake(128.17, 270.35))
        clip7Path.addCurveToPoint(CGPointMake(127.7, 268.57), controlPoint1: CGPointMake(128.51, 269.3), controlPoint2: CGPointMake(128.22, 268.74))
        clip7Path.addCurveToPoint(CGPointMake(126.44, 269.21), controlPoint1: CGPointMake(127.17, 268.4), controlPoint2: CGPointMake(126.61, 268.68))
        clip7Path.addCurveToPoint(CGPointMake(127.08, 270.47), controlPoint1: CGPointMake(126.27, 269.73), controlPoint2: CGPointMake(126.56, 270.3))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(138.92, 54.43))
        clip7Path.addCurveToPoint(CGPointMake(139.69, 53.24), controlPoint1: CGPointMake(139.46, 54.31), controlPoint2: CGPointMake(139.81, 53.78))
        clip7Path.addCurveToPoint(CGPointMake(138.51, 52.47), controlPoint1: CGPointMake(139.58, 52.7), controlPoint2: CGPointMake(139.05, 52.35))
        clip7Path.addCurveToPoint(CGPointMake(137.74, 53.66), controlPoint1: CGPointMake(137.97, 52.58), controlPoint2: CGPointMake(137.62, 53.12))
        clip7Path.addCurveToPoint(CGPointMake(138.92, 54.43), controlPoint1: CGPointMake(137.85, 54.2), controlPoint2: CGPointMake(138.38, 54.54))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(185.49, 273.53))
        clip7Path.addCurveToPoint(CGPointMake(186.26, 272.34), controlPoint1: CGPointMake(186.03, 273.42), controlPoint2: CGPointMake(186.38, 272.88))
        clip7Path.addCurveToPoint(CGPointMake(185.08, 271.57), controlPoint1: CGPointMake(186.15, 271.8), controlPoint2: CGPointMake(185.62, 271.46))
        clip7Path.addCurveToPoint(CGPointMake(184.31, 272.76), controlPoint1: CGPointMake(184.54, 271.69), controlPoint2: CGPointMake(184.19, 272.22))
        clip7Path.addCurveToPoint(CGPointMake(185.49, 273.53), controlPoint1: CGPointMake(184.42, 273.3), controlPoint2: CGPointMake(184.95, 273.65))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(87.73, 80.51))
        clip7Path.addCurveToPoint(CGPointMake(87.8, 79.1), controlPoint1: CGPointMake(88.14, 80.14), controlPoint2: CGPointMake(88.17, 79.51))
        clip7Path.addCurveToPoint(CGPointMake(86.39, 79.02), controlPoint1: CGPointMake(87.43, 78.69), controlPoint2: CGPointMake(86.8, 78.66))
        clip7Path.addCurveToPoint(CGPointMake(86.31, 80.44), controlPoint1: CGPointMake(85.98, 79.39), controlPoint2: CGPointMake(85.94, 80.03))
        clip7Path.addCurveToPoint(CGPointMake(87.73, 80.51), controlPoint1: CGPointMake(86.68, 80.85), controlPoint2: CGPointMake(87.32, 80.88))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(237.61, 246.98))
        clip7Path.addCurveToPoint(CGPointMake(237.69, 245.56), controlPoint1: CGPointMake(238.02, 246.61), controlPoint2: CGPointMake(238.06, 245.97))
        clip7Path.addCurveToPoint(CGPointMake(236.27, 245.49), controlPoint1: CGPointMake(237.32, 245.15), controlPoint2: CGPointMake(236.68, 245.12))
        clip7Path.addCurveToPoint(CGPointMake(236.2, 246.9), controlPoint1: CGPointMake(235.86, 245.86), controlPoint2: CGPointMake(235.83, 246.49))
        clip7Path.addCurveToPoint(CGPointMake(237.61, 246.98), controlPoint1: CGPointMake(236.57, 247.31), controlPoint2: CGPointMake(237.2, 247.34))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(267.57, 197.3))
        clip7Path.addCurveToPoint(CGPointMake(268.21, 198.56), controlPoint1: CGPointMake(267.4, 197.83), controlPoint2: CGPointMake(267.68, 198.39))
        clip7Path.addCurveToPoint(CGPointMake(269.47, 197.92), controlPoint1: CGPointMake(268.73, 198.73), controlPoint2: CGPointMake(269.3, 198.44))
        clip7Path.addCurveToPoint(CGPointMake(268.83, 196.66), controlPoint1: CGPointMake(269.64, 197.39), controlPoint2: CGPointMake(269.35, 196.83))
        clip7Path.addCurveToPoint(CGPointMake(267.57, 197.3), controlPoint1: CGPointMake(268.3, 196.49), controlPoint2: CGPointMake(267.74, 196.78))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(54.53, 128.08))
        clip7Path.addCurveToPoint(CGPointMake(55.17, 129.34), controlPoint1: CGPointMake(54.36, 128.61), controlPoint2: CGPointMake(54.65, 129.17))
        clip7Path.addCurveToPoint(CGPointMake(56.43, 128.7), controlPoint1: CGPointMake(55.7, 129.51), controlPoint2: CGPointMake(56.26, 129.22))
        clip7Path.addCurveToPoint(CGPointMake(55.79, 127.44), controlPoint1: CGPointMake(56.6, 128.17), controlPoint2: CGPointMake(56.32, 127.61))
        clip7Path.addCurveToPoint(CGPointMake(54.53, 128.08), controlPoint1: CGPointMake(55.27, 127.27), controlPoint2: CGPointMake(54.7, 127.56))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(244.49, 88.73))
        clip7Path.addCurveToPoint(CGPointMake(245.9, 88.8), controlPoint1: CGPointMake(244.86, 89.14), controlPoint2: CGPointMake(245.49, 89.17))
        clip7Path.addCurveToPoint(CGPointMake(245.98, 87.39), controlPoint1: CGPointMake(246.31, 88.43), controlPoint2: CGPointMake(246.34, 87.8))
        clip7Path.addCurveToPoint(CGPointMake(244.56, 87.31), controlPoint1: CGPointMake(245.61, 86.98), controlPoint2: CGPointMake(244.97, 86.94))
        clip7Path.addCurveToPoint(CGPointMake(244.49, 88.73), controlPoint1: CGPointMake(244.15, 87.68), controlPoint2: CGPointMake(244.12, 88.32))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(78.02, 238.61))
        clip7Path.addCurveToPoint(CGPointMake(79.44, 238.69), controlPoint1: CGPointMake(78.39, 239.02), controlPoint2: CGPointMake(79.03, 239.06))
        clip7Path.addCurveToPoint(CGPointMake(79.51, 237.27), controlPoint1: CGPointMake(79.85, 238.32), controlPoint2: CGPointMake(79.88, 237.68))
        clip7Path.addCurveToPoint(CGPointMake(78.1, 237.2), controlPoint1: CGPointMake(79.14, 236.86), controlPoint2: CGPointMake(78.51, 236.83))
        clip7Path.addCurveToPoint(CGPointMake(78.02, 238.61), controlPoint1: CGPointMake(77.69, 237.57), controlPoint2: CGPointMake(77.66, 238.2))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(270.57, 139.92))
        clip7Path.addCurveToPoint(CGPointMake(271.76, 140.69), controlPoint1: CGPointMake(270.69, 140.46), controlPoint2: CGPointMake(271.22, 140.81))
        clip7Path.addCurveToPoint(CGPointMake(272.53, 139.51), controlPoint1: CGPointMake(272.3, 140.58), controlPoint2: CGPointMake(272.65, 140.05))
        clip7Path.addCurveToPoint(CGPointMake(271.34, 138.74), controlPoint1: CGPointMake(272.42, 138.97), controlPoint2: CGPointMake(271.88, 138.62))
        clip7Path.addCurveToPoint(CGPointMake(270.57, 139.92), controlPoint1: CGPointMake(270.8, 138.85), controlPoint2: CGPointMake(270.46, 139.38))
        clip7Path.closePath()
        clip7Path.moveToPoint(CGPointMake(51.47, 186.49))
        clip7Path.addCurveToPoint(CGPointMake(52.66, 187.26), controlPoint1: CGPointMake(51.58, 187.03), controlPoint2: CGPointMake(52.12, 187.38))
        clip7Path.addCurveToPoint(CGPointMake(53.43, 186.08), controlPoint1: CGPointMake(53.2, 187.15), controlPoint2: CGPointMake(53.54, 186.62))
        clip7Path.addCurveToPoint(CGPointMake(52.24, 185.31), controlPoint1: CGPointMake(53.31, 185.54), controlPoint2: CGPointMake(52.78, 185.19))
        clip7Path.addCurveToPoint(CGPointMake(51.47, 186.49), controlPoint1: CGPointMake(51.7, 185.42), controlPoint2: CGPointMake(51.35, 185.95))
        clip7Path.closePath()
        clip7Path.usesEvenOddFillRule = true;

        clip7Path.addClip()


        //// Rectangle 4 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 162, 163)
        CGContextRotateCTM(context, 18 * CGFloat(M_PI) / 180)

        let rectangle4Path = UIBezierPath(rect: CGRectMake(-118, -118, 236, 236))
        fillColor10.setFill()
        rectangle4Path.fill()

        CGContextRestoreGState(context)


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// Group 13
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip 8
        var clip8Path = UIBezierPath()
        clip8Path.moveToPoint(CGPointMake(207.15, 61.6))
        clip8Path.addCurveToPoint(CGPointMake(208.47, 61.09), controlPoint1: CGPointMake(207.65, 61.82), controlPoint2: CGPointMake(208.24, 61.59))
        clip8Path.addCurveToPoint(CGPointMake(207.96, 59.77), controlPoint1: CGPointMake(208.69, 60.59), controlPoint2: CGPointMake(208.47, 59.99))
        clip8Path.addCurveToPoint(CGPointMake(206.64, 60.28), controlPoint1: CGPointMake(207.46, 59.54), controlPoint2: CGPointMake(206.87, 59.77))
        clip8Path.addCurveToPoint(CGPointMake(207.15, 61.6), controlPoint1: CGPointMake(206.42, 60.78), controlPoint2: CGPointMake(206.64, 61.37))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(116.04, 266.23))
        clip8Path.addCurveToPoint(CGPointMake(117.36, 265.72), controlPoint1: CGPointMake(116.54, 266.46), controlPoint2: CGPointMake(117.13, 266.23))
        clip8Path.addCurveToPoint(CGPointMake(116.85, 264.4), controlPoint1: CGPointMake(117.58, 265.22), controlPoint2: CGPointMake(117.36, 264.63))
        clip8Path.addCurveToPoint(CGPointMake(115.53, 264.91), controlPoint1: CGPointMake(116.35, 264.18), controlPoint2: CGPointMake(115.76, 264.41))
        clip8Path.addCurveToPoint(CGPointMake(116.04, 266.23), controlPoint1: CGPointMake(115.31, 265.41), controlPoint2: CGPointMake(115.53, 266.01))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(150.4, 52.61))
        clip8Path.addCurveToPoint(CGPointMake(151.29, 51.51), controlPoint1: CGPointMake(150.95, 52.55), controlPoint2: CGPointMake(151.35, 52.06))
        clip8Path.addCurveToPoint(CGPointMake(150.19, 50.62), controlPoint1: CGPointMake(151.23, 50.96), controlPoint2: CGPointMake(150.74, 50.56))
        clip8Path.addCurveToPoint(CGPointMake(149.3, 51.72), controlPoint1: CGPointMake(149.64, 50.68), controlPoint2: CGPointMake(149.24, 51.17))
        clip8Path.addCurveToPoint(CGPointMake(150.4, 52.61), controlPoint1: CGPointMake(149.36, 52.27), controlPoint2: CGPointMake(149.85, 52.67))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(173.81, 275.38))
        clip8Path.addCurveToPoint(CGPointMake(174.7, 274.28), controlPoint1: CGPointMake(174.36, 275.32), controlPoint2: CGPointMake(174.76, 274.83))
        clip8Path.addCurveToPoint(CGPointMake(173.6, 273.39), controlPoint1: CGPointMake(174.64, 273.73), controlPoint2: CGPointMake(174.15, 273.33))
        clip8Path.addCurveToPoint(CGPointMake(172.71, 274.49), controlPoint1: CGPointMake(173.05, 273.45), controlPoint2: CGPointMake(172.65, 273.94))
        clip8Path.addCurveToPoint(CGPointMake(173.81, 275.38), controlPoint1: CGPointMake(172.77, 275.04), controlPoint2: CGPointMake(173.26, 275.44))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(96.76, 73.2))
        clip8Path.addCurveToPoint(CGPointMake(96.98, 71.8), controlPoint1: CGPointMake(97.2, 72.87), controlPoint2: CGPointMake(97.3, 72.25))
        clip8Path.addCurveToPoint(CGPointMake(95.58, 71.58), controlPoint1: CGPointMake(96.65, 71.36), controlPoint2: CGPointMake(96.03, 71.26))
        clip8Path.addCurveToPoint(CGPointMake(95.36, 72.98), controlPoint1: CGPointMake(95.13, 71.91), controlPoint2: CGPointMake(95.03, 72.53))
        clip8Path.addCurveToPoint(CGPointMake(96.76, 73.2), controlPoint1: CGPointMake(95.68, 73.42), controlPoint2: CGPointMake(96.31, 73.52))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(228.42, 254.42))
        clip8Path.addCurveToPoint(CGPointMake(228.64, 253.02), controlPoint1: CGPointMake(228.87, 254.09), controlPoint2: CGPointMake(228.97, 253.47))
        clip8Path.addCurveToPoint(CGPointMake(227.24, 252.8), controlPoint1: CGPointMake(228.32, 252.58), controlPoint2: CGPointMake(227.69, 252.48))
        clip8Path.addCurveToPoint(CGPointMake(227.02, 254.2), controlPoint1: CGPointMake(226.8, 253.13), controlPoint2: CGPointMake(226.7, 253.75))
        clip8Path.addCurveToPoint(CGPointMake(228.42, 254.42), controlPoint1: CGPointMake(227.35, 254.64), controlPoint2: CGPointMake(227.97, 254.74))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(263.4, 208.15))
        clip8Path.addCurveToPoint(CGPointMake(263.91, 209.47), controlPoint1: CGPointMake(263.18, 208.65), controlPoint2: CGPointMake(263.41, 209.24))
        clip8Path.addCurveToPoint(CGPointMake(265.23, 208.96), controlPoint1: CGPointMake(264.41, 209.69), controlPoint2: CGPointMake(265.01, 209.47))
        clip8Path.addCurveToPoint(CGPointMake(264.72, 207.64), controlPoint1: CGPointMake(265.46, 208.46), controlPoint2: CGPointMake(265.23, 207.87))
        clip8Path.addCurveToPoint(CGPointMake(263.4, 208.15), controlPoint1: CGPointMake(264.22, 207.42), controlPoint2: CGPointMake(263.63, 207.64))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(58.77, 117.04))
        clip8Path.addCurveToPoint(CGPointMake(59.28, 118.36), controlPoint1: CGPointMake(58.54, 117.54), controlPoint2: CGPointMake(58.77, 118.13))
        clip8Path.addCurveToPoint(CGPointMake(60.6, 117.85), controlPoint1: CGPointMake(59.78, 118.58), controlPoint2: CGPointMake(60.37, 118.36))
        clip8Path.addCurveToPoint(CGPointMake(60.09, 116.53), controlPoint1: CGPointMake(60.82, 117.35), controlPoint2: CGPointMake(60.59, 116.76))
        clip8Path.addCurveToPoint(CGPointMake(58.77, 117.04), controlPoint1: CGPointMake(59.59, 116.31), controlPoint2: CGPointMake(58.99, 116.53))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(251.8, 97.76))
        clip8Path.addCurveToPoint(CGPointMake(253.2, 97.98), controlPoint1: CGPointMake(252.13, 98.2), controlPoint2: CGPointMake(252.75, 98.3))
        clip8Path.addCurveToPoint(CGPointMake(253.42, 96.58), controlPoint1: CGPointMake(253.64, 97.65), controlPoint2: CGPointMake(253.74, 97.03))
        clip8Path.addCurveToPoint(CGPointMake(252.02, 96.36), controlPoint1: CGPointMake(253.09, 96.13), controlPoint2: CGPointMake(252.47, 96.03))
        clip8Path.addCurveToPoint(CGPointMake(251.8, 97.76), controlPoint1: CGPointMake(251.58, 96.68), controlPoint2: CGPointMake(251.48, 97.31))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(70.58, 229.42))
        clip8Path.addCurveToPoint(CGPointMake(71.98, 229.64), controlPoint1: CGPointMake(70.91, 229.87), controlPoint2: CGPointMake(71.53, 229.97))
        clip8Path.addCurveToPoint(CGPointMake(72.2, 228.24), controlPoint1: CGPointMake(72.42, 229.32), controlPoint2: CGPointMake(72.52, 228.69))
        clip8Path.addCurveToPoint(CGPointMake(70.8, 228.02), controlPoint1: CGPointMake(71.87, 227.8), controlPoint2: CGPointMake(71.25, 227.7))
        clip8Path.addCurveToPoint(CGPointMake(70.58, 229.42), controlPoint1: CGPointMake(70.36, 228.35), controlPoint2: CGPointMake(70.26, 228.97))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(272.39, 151.4))
        clip8Path.addCurveToPoint(CGPointMake(273.49, 152.29), controlPoint1: CGPointMake(272.45, 151.95), controlPoint2: CGPointMake(272.94, 152.35))
        clip8Path.addCurveToPoint(CGPointMake(274.38, 151.19), controlPoint1: CGPointMake(274.04, 152.23), controlPoint2: CGPointMake(274.44, 151.74))
        clip8Path.addCurveToPoint(CGPointMake(273.28, 150.3), controlPoint1: CGPointMake(274.32, 150.64), controlPoint2: CGPointMake(273.83, 150.24))
        clip8Path.addCurveToPoint(CGPointMake(272.39, 151.4), controlPoint1: CGPointMake(272.73, 150.36), controlPoint2: CGPointMake(272.33, 150.85))
        clip8Path.closePath()
        clip8Path.moveToPoint(CGPointMake(49.62, 174.81))
        clip8Path.addCurveToPoint(CGPointMake(50.72, 175.7), controlPoint1: CGPointMake(49.68, 175.36), controlPoint2: CGPointMake(50.17, 175.76))
        clip8Path.addCurveToPoint(CGPointMake(51.61, 174.6), controlPoint1: CGPointMake(51.27, 175.64), controlPoint2: CGPointMake(51.67, 175.15))
        clip8Path.addCurveToPoint(CGPointMake(50.51, 173.71), controlPoint1: CGPointMake(51.55, 174.05), controlPoint2: CGPointMake(51.06, 173.65))
        clip8Path.addCurveToPoint(CGPointMake(49.62, 174.81), controlPoint1: CGPointMake(49.96, 173.77), controlPoint2: CGPointMake(49.56, 174.26))
        clip8Path.closePath()
        clip8Path.usesEvenOddFillRule = true;

        clip8Path.addClip()


        //// Rectangle 5 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 162, 163)
        CGContextRotateCTM(context, 24 * CGFloat(M_PI) / 180)

        let rectangle5Path = UIBezierPath(rect: CGRectMake(-118, -118, 236, 236))
        fillColor10.setFill()
        rectangle5Path.fill()

        CGContextRestoreGState(context)


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// ClockHighlightGroup
        CGContextSaveGState(context)
        CGContextSetAlpha(context, 0.67)
        CGContextBeginTransparencyLayer(context, nil)


        //// Bezier 9 Drawing
        var bezier9Path = UIBezierPath()
        bezier9Path.moveToPoint(CGPointMake(116.96, 186.29))
        bezier9Path.addCurveToPoint(CGPointMake(172.17, 117.55), controlPoint1: CGPointMake(116.96, 134.16), controlPoint2: CGPointMake(137.28, 120.87))
        bezier9Path.addCurveToPoint(CGPointMake(149.25, 58), controlPoint1: CGPointMake(207.06, 114.23), controlPoint2: CGPointMake(205.73, 58))
        bezier9Path.addCurveToPoint(CGPointMake(47, 160.25), controlPoint1: CGPointMake(92.78, 58), controlPoint2: CGPointMake(47, 103.78))
        bezier9Path.addCurveToPoint(CGPointMake(116.96, 186.29), controlPoint1: CGPointMake(47, 216.73), controlPoint2: CGPointMake(116.96, 238.43))
        bezier9Path.closePath()
        bezier9Path.usesEvenOddFillRule = true;

        CGContextSaveGState(context)
        bezier9Path.addClip()
        CGContextDrawLinearGradient(context, gradient,
            CGPointMake(168.19, 63.89),
            CGPointMake(47, 182.53),
            UInt32(kCGGradientDrawsBeforeStartLocation) | UInt32(kCGGradientDrawsAfterEndLocation))
        CGContextRestoreGState(context)


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// Group 18
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip 12
        let clip12Path = UIBezierPath(rect: CGRectMake(149, 150.05, 30, 32))
        clip12Path.addClip()


        //// Oval 9 Drawing
        var oval9Path = UIBezierPath(ovalInRect: CGRectMake(100, 161.05, 4, 4))
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, shadow6.shadowOffset, shadow6.shadowBlurRadius, (shadow6.shadowColor as! UIColor).CGColor)
        fillColor.setFill()
        oval9Path.fill()
        CGContextRestoreGState(context)



        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// Oval 10 Drawing
        var oval10Path = UIBezierPath(ovalInRect: CGRectMake(160, 161.05, 4, 4))
        fillColor8.setFill()
        oval10Path.fill()




        //// DateGroup
        //// DateGroupBG
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip 9
        var clip9Path = UIBezierPath()
        clip9Path.moveToPoint(CGPointMake(215, 161))
        clip9Path.addCurveToPoint(CGPointMake(217, 159), controlPoint1: CGPointMake(215, 159.89), controlPoint2: CGPointMake(215.89, 159))
        clip9Path.addLineToPoint(CGPointMake(249, 159))
        clip9Path.addCurveToPoint(CGPointMake(251, 161), controlPoint1: CGPointMake(250.1, 159), controlPoint2: CGPointMake(251, 159.89))
        clip9Path.addLineToPoint(CGPointMake(251, 175))
        clip9Path.addCurveToPoint(CGPointMake(249, 177), controlPoint1: CGPointMake(251, 176.11), controlPoint2: CGPointMake(250.11, 177))
        clip9Path.addLineToPoint(CGPointMake(217, 177))
        clip9Path.addCurveToPoint(CGPointMake(215, 175), controlPoint1: CGPointMake(215.9, 177), controlPoint2: CGPointMake(215, 176.11))
        clip9Path.addLineToPoint(CGPointMake(215, 161))
        clip9Path.closePath()
        clip9Path.usesEvenOddFillRule = true;

        clip9Path.addClip()


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRectMake(210, 154, 46, 28))
        fillColor11.setFill()
        rectanglePath.fill()


        //// Bezier 5 Drawing
        var bezier5Path = UIBezierPath()
        bezier5Path.moveToPoint(CGPointMake(234.45, 159))
        bezier5Path.addLineToPoint(CGPointMake(254.45, 159))
        bezier5Path.addLineToPoint(CGPointMake(254.45, 177))
        bezier5Path.addLineToPoint(CGPointMake(234.45, 177))
        bezier5Path.addCurveToPoint(CGPointMake(235, 168), controlPoint1: CGPointMake(234.81, 174.05), controlPoint2: CGPointMake(235, 171.05))
        bezier5Path.addCurveToPoint(CGPointMake(234.45, 159), controlPoint1: CGPointMake(235, 164.95), controlPoint2: CGPointMake(234.81, 161.95))
        bezier5Path.closePath()
        bezier5Path.usesEvenOddFillRule = true;

        fillColor12.setFill()
        bezier5Path.fill()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)


        //// DateInMonthLabel Drawing
        let dateInMonthLabelRect = CGRectMake(238, 161, 8.9, 13)
        let dateInMonthLabelStyle = NSParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        dateInMonthLabelStyle.alignment = NSTextAlignment.Center

        let dateInMonthLabelFontAttributes = [NSFontAttributeName: UIFont(name: "HelveticaNeue", size: 8)!, NSForegroundColorAttributeName: textForeground, NSParagraphStyleAttributeName: dateInMonthLabelStyle]

        let dateInMonthLabelTextHeight: CGFloat = NSString(string: dateInMonth).boundingRectWithSize(CGSizeMake(dateInMonthLabelRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: dateInMonthLabelFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, dateInMonthLabelRect);
        NSString(string: dateInMonth).drawInRect(CGRectMake(dateInMonthLabelRect.minX, dateInMonthLabelRect.minY + (dateInMonthLabelRect.height - dateInMonthLabelTextHeight) / 2, dateInMonthLabelRect.width, dateInMonthLabelTextHeight), withAttributes: dateInMonthLabelFontAttributes)
        CGContextRestoreGState(context)


        //// DateInWeekLabel Drawing
        let dateInWeekLabelRect = CGRectMake(215, 160, 19, 14)
        let dateInWeekLabelStyle = NSParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        dateInWeekLabelStyle.alignment = NSTextAlignment.Center

        let dateInWeekLabelFontAttributes = [NSFontAttributeName: UIFont(name: "HelveticaNeue", size: 8)!, NSForegroundColorAttributeName: textForeground2, NSParagraphStyleAttributeName: dateInWeekLabelStyle]

        let dateInWeekLabelTextHeight: CGFloat = NSString(string: dateInWeek).boundingRectWithSize(CGSizeMake(dateInWeekLabelRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: dateInWeekLabelFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, dateInWeekLabelRect);
        NSString(string: dateInWeek).drawInRect(CGRectMake(dateInWeekLabelRect.minX, dateInWeekLabelRect.minY + (dateInWeekLabelRect.height - dateInWeekLabelTextHeight) / 2, dateInWeekLabelRect.width, dateInWeekLabelTextHeight), withAttributes: dateInWeekLabelFontAttributes)
        CGContextRestoreGState(context)




        //// HourArrowGroup
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 162, 163)
        CGContextRotateCTM(context, -hourArrowAngle * CGFloat(M_PI) / 180)



        //// MinuteBezierGroup
        CGContextSaveGState(context)
        CGContextBeginTransparencyLayer(context, nil)

        //// Clip Clip 11
        var clip11Path = UIBezierPath()
        clip11Path.moveToPoint(CGPointMake(3.8, -10.28))
        clip11Path.addCurveToPoint(CGPointMake(10.48, 3.65), controlPoint1: CGPointMake(9.45, -8.25), controlPoint2: CGPointMake(12.44, -2.05))
        clip11Path.addCurveToPoint(CGPointMake(-3.5, 10.47), controlPoint1: CGPointMake(8.5, 9.39), controlPoint2: CGPointMake(2.24, 12.45))
        clip11Path.addCurveToPoint(CGPointMake(-10.32, -3.51), controlPoint1: CGPointMake(-9.25, 8.49), controlPoint2: CGPointMake(-12.3, 2.23))
        clip11Path.addCurveToPoint(CGPointMake(-3.89, -10.19), controlPoint1: CGPointMake(-9.23, -6.7), controlPoint2: CGPointMake(-6.81, -9.06))
        clip11Path.addLineToPoint(CGPointMake(-2.16, -61.24))
        clip11Path.addCurveToPoint(CGPointMake(-0.09, -63.24), controlPoint1: CGPointMake(-2.12, -62.34), controlPoint2: CGPointMake(-1.2, -63.24))
        clip11Path.addLineToPoint(CGPointMake(0.9, -63.24))
        clip11Path.addCurveToPoint(CGPointMake(2.94, -61.24), controlPoint1: CGPointMake(2.01, -63.24), controlPoint2: CGPointMake(2.92, -62.34))
        clip11Path.addLineToPoint(CGPointMake(3.8, -10.28))
        clip11Path.closePath()
        clip11Path.moveToPoint(CGPointMake(-1.23, 3.85))
        clip11Path.addCurveToPoint(CGPointMake(3.86, 1.37), controlPoint1: CGPointMake(0.86, 4.57), controlPoint2: CGPointMake(3.14, 3.46))
        clip11Path.addCurveToPoint(CGPointMake(1.38, -3.71), controlPoint1: CGPointMake(4.58, -0.72), controlPoint2: CGPointMake(3.47, -2.99))
        clip11Path.addCurveToPoint(CGPointMake(-3.71, -1.23), controlPoint1: CGPointMake(-0.71, -4.43), controlPoint2: CGPointMake(-2.99, -3.32))
        clip11Path.addCurveToPoint(CGPointMake(-1.23, 3.85), controlPoint1: CGPointMake(-4.42, 0.85), controlPoint2: CGPointMake(-3.31, 3.13))
        clip11Path.closePath()
        clip11Path.usesEvenOddFillRule = true;

        clip11Path.addClip()


        //// Rectangle 7 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 2.8, -25.05)
        CGContextRotateCTM(context, 19 * CGFloat(M_PI) / 180)

        let rectangle7Path = UIBezierPath(rect: CGRectMake(-21.58, -40.62, 43.15, 81.25))
        fillColor5.setFill()
        rectangle7Path.fill()

        CGContextRestoreGState(context)


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)



        CGContextRestoreGState(context)


        //// MinuteArrowGroup
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 162, 163.05)
        CGContextRotateCTM(context, -minuteArrowAngle * CGFloat(M_PI) / 180)



        //// MinuteArrowBezier Drawing
        var minuteArrowBezierPath = UIBezierPath()
        minuteArrowBezierPath.moveToPoint(CGPointMake(3.65, -5.6))
        minuteArrowBezierPath.addCurveToPoint(CGPointMake(6.39, -2.23), controlPoint1: CGPointMake(4.86, -4.82), controlPoint2: CGPointMake(5.83, -3.67))
        minuteArrowBezierPath.addCurveToPoint(CGPointMake(2.36, 6.81), controlPoint1: CGPointMake(7.77, 1.38), controlPoint2: CGPointMake(5.97, 5.43))
        minuteArrowBezierPath.addCurveToPoint(CGPointMake(-6.68, 2.79), controlPoint1: CGPointMake(-1.25, 8.2), controlPoint2: CGPointMake(-5.3, 6.4))
        minuteArrowBezierPath.addCurveToPoint(CGPointMake(-4.12, -5.49), controlPoint1: CGPointMake(-7.87, -0.3), controlPoint2: CGPointMake(-6.73, -3.7))
        minuteArrowBezierPath.addLineToPoint(CGPointMake(-2.27, -95.99))
        minuteArrowBezierPath.addCurveToPoint(CGPointMake(-0.23, -97.99), controlPoint1: CGPointMake(-2.25, -97.1), controlPoint2: CGPointMake(-1.34, -97.99))
        minuteArrowBezierPath.addCurveToPoint(CGPointMake(1.81, -95.99), controlPoint1: CGPointMake(0.87, -97.99), controlPoint2: CGPointMake(1.79, -97.1))
        minuteArrowBezierPath.addLineToPoint(CGPointMake(3.65, -5.6))
        minuteArrowBezierPath.addLineToPoint(CGPointMake(3.65, -5.6))
        minuteArrowBezierPath.closePath()
        minuteArrowBezierPath.usesEvenOddFillRule = true;

        fillColor6.setFill()
        minuteArrowBezierPath.fill()



        CGContextRestoreGState(context)


        //// SecondArrowGroup
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 162, 163)



        //// SecondArrowBezier Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 0, 0.05)
        CGContextRotateCTM(context, -secondArrowAngle * CGFloat(M_PI) / 180)

        var secondArrowBezierPath = UIBezierPath()
        secondArrowBezierPath.moveToPoint(CGPointMake(1.91, -3.56))
        secondArrowBezierPath.addCurveToPoint(CGPointMake(2.29, -3.33), controlPoint1: CGPointMake(2.04, -3.49), controlPoint2: CGPointMake(2.17, -3.41))
        secondArrowBezierPath.addCurveToPoint(CGPointMake(3.28, 2.24), controlPoint1: CGPointMake(4.1, -2.06), controlPoint2: CGPointMake(4.54, 0.43))
        secondArrowBezierPath.addCurveToPoint(CGPointMake(-2.29, 3.23), controlPoint1: CGPointMake(2.01, 4.05), controlPoint2: CGPointMake(-0.48, 4.49))
        secondArrowBezierPath.addCurveToPoint(CGPointMake(-3.28, -2.34), controlPoint1: CGPointMake(-4.1, 1.96), controlPoint2: CGPointMake(-4.54, -0.53))
        secondArrowBezierPath.addCurveToPoint(CGPointMake(-2.01, -3.51), controlPoint1: CGPointMake(-2.93, -2.84), controlPoint2: CGPointMake(-2.5, -3.23))
        secondArrowBezierPath.addLineToPoint(CGPointMake(-1.07, -89.15))
        secondArrowBezierPath.addCurveToPoint(CGPointMake(0.93, -91.13), controlPoint1: CGPointMake(-1.06, -90.24), controlPoint2: CGPointMake(-0.17, -91.13))
        secondArrowBezierPath.addLineToPoint(CGPointMake(-1.03, -91.13))
        secondArrowBezierPath.addCurveToPoint(CGPointMake(0.97, -89.15), controlPoint1: CGPointMake(0.07, -91.13), controlPoint2: CGPointMake(0.96, -90.25))
        secondArrowBezierPath.addLineToPoint(CGPointMake(1.91, -3.56))
        secondArrowBezierPath.addLineToPoint(CGPointMake(1.91, -3.56))
        secondArrowBezierPath.addLineToPoint(CGPointMake(1.91, -3.56))
        secondArrowBezierPath.closePath()
        secondArrowBezierPath.usesEvenOddFillRule = true;

        fillColor7.setFill()
        secondArrowBezierPath.fill()

        CGContextRestoreGState(context)



        CGContextRestoreGState(context)
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
