//
//  SliderStyleKit.swift
//  ProjectName
//
//  Created by Pham Nguyen Nhat Trung on 8/21/15.
//  Copyright (c) 2015 Mirum. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SliderStyleKit : NSObject {

    //// Drawing Methods

    public class func drawSliderThumb(#frame: CGRect) {

        //// thumb Drawing
        var thumbPath = UIBezierPath()
        thumbPath.moveToPoint(CGPointMake(frame.minX + 0.91071 * frame.width, frame.minY + 0.57143 * frame.height))
        thumbPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.24286 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.91071 * frame.width, frame.minY + 0.38996 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.72683 * frame.width, frame.minY + 0.24286 * frame.height))
        thumbPath.addCurveToPoint(CGPointMake(frame.minX + 0.08929 * frame.width, frame.minY + 0.57143 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.27317 * frame.width, frame.minY + 0.24286 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.08929 * frame.width, frame.minY + 0.38996 * frame.height))
        thumbPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.90000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.08929 * frame.width, frame.minY + 0.75289 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.27317 * frame.width, frame.minY + 0.90000 * frame.height))
        thumbPath.addCurveToPoint(CGPointMake(frame.minX + 0.91071 * frame.width, frame.minY + 0.57143 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.72683 * frame.width, frame.minY + 0.90000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.91071 * frame.width, frame.minY + 0.75289 * frame.height))
        thumbPath.closePath()
        thumbPath.moveToPoint(CGPointMake(frame.minX + 0.33929 * frame.width, frame.minY + 0.27143 * frame.height))
        thumbPath.addLineToPoint(CGPointMake(frame.minX + 0.51786 * frame.width, frame.minY + 0.07143 * frame.height))
        thumbPath.addLineToPoint(CGPointMake(frame.minX + 0.69643 * frame.width, frame.minY + 0.27143 * frame.height))
        UIColor.blackColor().setStroke()
        thumbPath.lineWidth = 3
        thumbPath.stroke()
    }

}
