//
//  UIColor+AlarmApp.swift
//
//  Generated by Zeplin on 8/11/15.
//  Copyright (c) 2015 Pham Nguyen Nhat Trung. All rights reserved.
//

import UIKit

extension UIColor {
    class func untMarineColor() -> UIColor {
        return UIColor(red: 9.0 / 255.0, green: 39.0 / 255.0, blue: 73.0 / 255.0, alpha: 1.0)
    }

    class func untAzulColor() -> UIColor {
        return UIColor(red: 43.0 / 255.0, green: 100.0 / 255.0, blue: 243.0 / 255.0, alpha: 1.0)
    }

    class func untCoralColor() -> UIColor {
        return UIColor(red: 247.0 / 255.0, green: 70.0 / 255.0, blue: 70.0 / 255.0, alpha: 1.0)
    }

    class func untOrangeYellowColor() -> UIColor {
        return UIColor(red: 255.0 / 255.0, green: 160.0 / 255.0, blue: 0.0, alpha: 1.0)
    }

    class func untWhiteColor() -> UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 1.0)
    }

    class func untLightWhiteColor() -> UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 0.15)
    }

    class func untTranswhiteColor() -> UIColor {
        return UIColor(white: 215.0 / 255.0, alpha: 0.0)
    }

    class func untLightishBlueColor() -> UIColor {
        return UIColor(red: 66.0 / 255.0, green: 121.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
    }

    class func untTransparentColor() -> UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 0.0)
    }

    class func untDeepSkyBlueColor() -> UIColor {
        return UIColor(red: 11.0 / 255.0, green: 118.0 / 255.0, blue: 241.0 / 255.0, alpha: 1.0)
    }

    class func untDustyOrangeColor() -> UIColor {
        return UIColor(red: 237.0 / 255.0, green: 111.0 / 255.0, blue: 75.0 / 255.0, alpha: 1.0)
    }

    class func untGreyishBrownColor() -> UIColor {
        return UIColor(white: 67.0 / 255.0, alpha: 1.0)
    }

    class func untBlackColor() -> UIColor {
        return UIColor(white: 33.0 / 255.0, alpha: 1.0)
    }

    class func untGrayColor() -> UIColor {
        return UIColor(white: 229.0 / 255.0, alpha: 1.0)
    }

    class func untSkyBlueColor() -> UIColor {
        return UIColor(red: 109.0 / 255.0, green: 173.0 / 255.0, blue: 248.0 / 255.0, alpha: 1.0)
    }

}
